apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - canary.yaml
  - deployment.yaml
  - hpa.yaml
images:
  - name: ghcr.io/stefanprodan/podinfo
    newName: ghcr.io/stefanprodan/podinfo
    newTag: 6.1.0
patchesJson6902:
- path: deployment.patch.yaml
  target:
      group: apps
      kind: Deployment
      name: backend
      version: v1
